#!/bin/sh

vMODEM="any"
vMMCLI_CMD="mmcli -m ${vMODEM} -v"

ARG1=$1
ARG2=$2

command -v mmcli >/dev/null 2>&1 || { echo "ModemManager not installed..."; exit 1; }

case $ARG1 in
        status)
                ${vMMCLI_CMD} --3gpp-ussd-status
                ;;
        cancel)
                ${vMMCLI_CMD} --3gpp-ussd-cancel
                ;;
        resp)
                ${vMMCLI_CMD} --3gpp-ussd-respond=$ARG2
                ;;
        help)
                echo
                echo "Пример: ussd *100#"
                echo "Ответит - ваш баланс равен 100 рублей"
                echo
                echo "Если ваш запрос ussd просит ответита, введите:"
                echo "ussd resp 1"
                echo "Будет означать что вы ответили цифрой 1"
                echo
                echo "ussd status"
                echo "Показывает есть ли у вас ussd запросы требующие ответа"
                echo
                echo "ussd cancel"
                echo "Отменит запрос требующий ответа"
                echo
                ;;
        *)
                ${vMMCLI_CMD} --3gpp-ussd-initiate=$ARG1
                ;;
esac
