# https://firmware-selector.openwrt.org/?version=24.10.4&target=mediatek%2Ffilogic&id=xiaomi_mi-router-ax3000t
# Xiaomi Mi Router AX3000T [ROUTERICH mod]
6in4
6to4
acl
adb
adblock
-amneziawg-tools
-atinout
-automodem
avahi-nodbus-daemon
base-files
bind-dig
bind-libs
block-mount
bridger
busybox
ca-bundle
cgi-io
chat
comgt
comgt-ncm
coreutils
coreutils-base64
coreutils-sleep
coreutils-sort
curl
dbus
ddns-scripts
ddns-scripts-services
dnsmasq-full
dnsproxy
-doh-proxy
dropbear
e2fsprogs
eip197-mini-firmware
etherwake
fdisk
firewall4
fitblk
fstools
fwtool
getdns
getrandom
glib2
gzip
hdparm
hostapd-common
hostapd-utils
htop
https-dns-proxy
iconv
-internet-detector
ip-tiny
iperf3
ipset
iw
iwinfo
jansson4
jq
jshn
jsonfilter
kernel
-kmod-amneziawg
kmod-asn1-decoder
kmod-br-netfilter
kmod-cfg80211
kmod-crypto-aead
kmod-crypto-arc4
kmod-crypto-authenc
kmod-crypto-ccm
kmod-crypto-cmac
kmod-crypto-crc32c
kmod-crypto-ctr
kmod-crypto-des
kmod-crypto-ecb
kmod-crypto-gcm
kmod-crypto-geniv
kmod-crypto-gf128
kmod-crypto-ghash
kmod-crypto-hash
kmod-crypto-hmac
kmod-crypto-hw-safexcel
kmod-crypto-kpp
kmod-crypto-lib-chacha20
kmod-crypto-lib-chacha20poly1305
kmod-crypto-lib-curve25519
kmod-crypto-lib-poly1305
kmod-crypto-manager
kmod-crypto-md5
kmod-crypto-null
kmod-crypto-rng
kmod-crypto-seqiv
kmod-crypto-sha1
kmod-crypto-sha256
kmod-crypto-sha3
kmod-crypto-sha512
kmod-crypto-user
kmod-fs-exfat
kmod-fs-ext4
kmod-fs-ksmbd
kmod-fs-netfs
kmod-fs-ntfs3
kmod-fs-smbfs-common
kmod-fs-vfat
kmod-gpio-button-hotplug
kmod-gre
kmod-hwmon-core
kmod-inet-diag
kmod-ipt-conntrack
kmod-ipt-core
kmod-ipt-ipset
kmod-ipt-nat
kmod-iptunnel
kmod-iptunnel4
kmod-l2tp
kmod-l2tp-eth
kmod-l2tp-ip
kmod-leds-gpio
kmod-lib-crc-ccitt
kmod-lib-crc16
kmod-lib-crc32c
kmod-lib-lz4
kmod-lib-lz4-decompress
kmod-lib-lzo
kmod-lib-textsearch
kmod-libphy
kmod-lp
kmod-mac80211
kmod-mii
kmod-mppe
kmod-mt76-connac
kmod-mt76-core
kmod-mt7915e
kmod-mt7981-firmware
kmod-mtd-rw
-kmod-natflow
kmod-nf-conntrack
kmod-nf-conntrack-netlink
kmod-nf-conntrack6
kmod-nf-flow
kmod-nf-ipt
kmod-nf-log
kmod-nf-log6
kmod-nf-nat
kmod-nf-nathelper-extra
kmod-nf-reject
kmod-nf-reject6
kmod-nf-tproxy
kmod-nfnetlink
kmod-nfnetlink-queue
kmod-nft-core
kmod-nft-fib
kmod-nft-nat
kmod-nft-offload
kmod-nft-queue
kmod-nft-tproxy
kmod-nls-base
kmod-nls-cp437
kmod-nls-iso8859-1
kmod-nls-ucs2-utils
kmod-nls-utf8
kmod-oid-registry
kmod-phy-aquantia
kmod-ppdev
kmod-ppp
kmod-pppoe
kmod-pppol2tp
kmod-pppox
kmod-pptp
kmod-sched-act-vlan
kmod-sched-bpf
kmod-sched-core
kmod-sched-flower
kmod-scsi-core
kmod-sit
kmod-slhc
kmod-thermal
kmod-tun
kmod-udptunnel4
kmod-udptunnel6
kmod-usb-acm
kmod-usb-core
kmod-usb-net
kmod-usb-net-cdc-ether
kmod-usb-net-cdc-mbim
kmod-usb-net-cdc-ncm
kmod-usb-net-huawei-cdc-ncm
kmod-usb-net-qmi-wwan
kmod-usb-net-rndis
kmod-usb-printer
kmod-usb-serial
kmod-usb-serial-option
kmod-usb-serial-qualcomm
kmod-usb-serial-wwan
kmod-usb-storage
kmod-usb-storage-extras
kmod-usb-storage-uas
kmod-usb-wdm
kmod-usb-xhci-hcd
kmod-usb-xhci-mtk
kmod-usb3
ksmbd-avahi-service
-ksmbd-rrplug
ksmbd-server
libacl
libatomic1
libattr
libavahi-nodbus-support
libblkid1
libblobmsg-json20240329
libbpf1
libc
libcap
libcap-ng
libcares
libcharset1
libcomerr0
libcurl4
libdaemon
libdbus
libe2p2
libelf1
libev
libevdev
libexpat
libext2fs2
libfdisk1
libffi
libgcc1
libgmp10
libiconv-full2
libiperf3
libipset13
libiwinfo-data
libiwinfo20230701
libjson-c5
libjson-script20240329
liblua5.1.5
liblucihttp-lua
liblucihttp-ucode
liblucihttp0
liblz4-1
liblzo2
libmbedtls21
libmbim
libminiupnpc
libmnl0
libmount1
libnatpmp1
libncurses6
libnetfilter-conntrack3
libnetfilter-queue1
libnettle8
libnfnetlink0
libnftnl11
libnghttp2-14
libnl-core200
libnl-genl200
libnl-tiny1
libopenssl-conf
libopenssl-legacy
libopenssl3
libpcre2
libpthread
libqmi
libqrencode
libqrtr-glib
librt
libsmartcols1
libss2
libssh2-1
libstdcpp6
libubox20240329
libubus-lua
libubus20250102
libuci-lua
libuci20250120
libuclient20201210
libucode20230711
libudebug
libudev-zero
liburcu
libusb-1.0-0
libustream-mbedtls20201210
libuuid1
libuv1
libwebsockets-full
libyaml
logd
lua
lua-bit32
-lua-ipops
luaposix
-luci-app-access-control
-luci-app-amneziawg
luci-app-adblock
-luci-app-atinout
luci-app-ddns
-luci-app-block-users
-luci-app-dns-failsafe-proxy
-luci-app-doh-proxy
luci-app-filemanager
luci-app-firewall
-luci-app-hostacl
-luci-app-internet-detector
luci-app-ksmbd
-luci-app-ledcontrol
-luci-app-log-viewer
-luci-app-mmconfig
-luci-app-modemband
-luci-app-modeminfo
luci-app-package-manager
-luci-app-podkop
-luci-app-smstools3
-luci-app-stubby
-luci-app-tailscale
luci-app-ttyd
luci-app-upnp
-luci-app-urllogger
-luci-app-ussd
-luci-app-wdoc
-luci-app-wdoc-singbox
-luci-app-wdoc-warp
-luci-app-wdoc-wg
-luci-app-wizard
luci-app-wol
-luci-app-youtubeUnblock
-luci-app-zapret
-luci-app-zerotier
luci-base
luci-compat
-luci-i18n-access-control-ru
-luci-i18n-amneziawg-ru
luci-i18n-adblock-ru
-luci-i18n-atinout-ru
luci-i18n-base-ru
luci-i18n-ddns-ru
-luci-i18n-doh-proxy-ru
luci-i18n-filemanager-ru
luci-i18n-firewall-ru
-luci-i18n-internet-detector-ru
luci-i18n-ksmbd-ru
-luci-i18n-ledcontrol-ru
-luci-i18n-log-ru
-luci-i18n-mmconfig-ru
-luci-i18n-modemband-ru
-luci-i18n-modeminfo-ru
luci-i18n-package-manager-ru
-luci-i18n-podkop-ru
-luci-i18n-smstools3-ru
-luci-i18n-stubby-ru
-luci-i18n-tailscale-ru
luci-i18n-ttyd-ru
luci-i18n-upnp-ru
-luci-i18n-ussd-ru
-luci-i18n-wdoc-singbox-ru
-luci-i18n-wdoc-warp-ru
-luci-i18n-wdoc-wg-ru
luci-i18n-wol-ru
-luci-i18n-zerotier-ru
luci-lib-base
luci-lib-ip
luci-lib-jsonc
luci-lib-nixio
luci-lib-uqr
luci-light
luci-lua-runtime
luci-mod-admin-full
luci-mod-network
luci-mod-status
luci-mod-system
luci-proto-ipv6
luci-proto-mbim
luci-proto-modemmanager
luci-proto-ncm
luci-proto-ppp
-luci-proto-xmm
luci-ssl
luci-theme-bootstrap
-luci-theme-routerich
mbim-utils
mc
miniupnpd-nftables
-modemband
-modeminfo
-modeminfo-qmi
-modeminfo-serial-dell
-modeminfo-serial-fibocom
-modeminfo-serial-gosun
-modeminfo-serial-huawei
-modeminfo-serial-meig
-modeminfo-serial-mikrotik
-modeminfo-serial-quectel
-modeminfo-serial-sierra
-modeminfo-serial-simcom
-modeminfo-serial-styx
-modeminfo-serial-telit
-modeminfo-serial-thales
-modeminfo-serial-tw
-modeminfo-serial-xmm
-modeminfo-serial-yuge
-modeminfo-serial-zte
modemmanager
mt7981-wo-firmware
mtd
mtr
nano-full
netifd
nftables-json
odhcp6c
odhcpd-ipv6only
openwrt-keyring
-opera-proxy
opkg
-podkop
ppp
ppp-mod-pppoe
ppp-mod-pppol2tp
ppp-mod-pptp
pppoe-discovery
procd
procd-seccomp
procd-ujail
px5g-mbedtls
qmi-utils
qrencode
resolveip
-routerich-defaults
rpcd
rpcd-mod-file
rpcd-mod-iwinfo
rpcd-mod-luci
rpcd-mod-rrdns
rpcd-mod-ucode
sing-box-tiny
-smount
sms-tool
smstools3
stubby
-tailscale-lite
terminfo
tmux
ttyd
ubi-utils
uboot-envtools
ubox
ubus
ubusd
uci
uclient-fetch
ucode
ucode-mod-fs
ucode-mod-html
ucode-mod-lua
ucode-mod-math
ucode-mod-nl80211
ucode-mod-rtnl
ucode-mod-ubus
ucode-mod-uci
ucode-mod-uloop
uhttpd
uhttpd-mod-ubus
umbim
unzip
uqmi
urandom-seed
urngd
usb-modeswitch
usbids
usbutils
usign
-wdoc
-wdoc-singbox
-wdoc-warp
-wdoc-wg
wget-ssl
whois
wifi-scripts
wireless-regdb
wpad-openssl
wsdd2
wwan
xl2tpd
-xmm-modem
-youtubeUnblock
-zapret
-zerotier-lite
zlib
